ccflags-y := -Iinclude/drm

obj-$(CONFIG_DRM_NXP_PTN3460) += nxp-ptn3460.o
obj-$(CONFIG_DRM_PARADE_PS8622) += parade-ps8622.o
obj-$(CONFIG_DRM_RK1000) += rk1000.o
obj-$(CONFIG_DRM_DUMB_VGA_DAC) += dumb-vga-dac.o
obj-$(CONFIG_DRM_LONTIUM_LT8912) += lt8912.o
obj-$(CONFIG_DRM_CHIPONE_ICN6211) += icn6211.o
obj-$(CONFIG_DRM_TI_SN65DSI86) += ti-sn65dsi86.o
obj-$(CONFIG_DRM_TOSHIBA_TC358770) += tc358770.o
obj-$(CONFIG_DRM_IT6151) += ite6151.o

obj-y += analogix/
obj-y += synopsys/
